---
- name: Установить Zabbix Agent
  apt:
    name: zabbix-agent
    state: present

- name: Настроить Zabbix Agent
  template:
    src: zabbix_agent/templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Запустить Zabbix Agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes

